


modLoader="javafml" 
loaderVersion="[35,)" 
license="All rights reserved"
issueTrackerURL="http://my.issue.tracker/" 

[[mods]] 
modId="emerald_expansion" 
version="1.0" 
displayName="Emerald Expansion" 
logoFile="examplemod.png"
description='''
mod
''' 
